# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadoria',
            name='img_name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
