# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_mercadoria_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
